FROM python:3.10.5-slim-buster

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update && \
    apt-get install -y libpq-dev gcc && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /code
WORKDIR /code

COPY . /code/

RUN pip install --upgrade pip && \
    pip install -r requirements/develop.txt
