# Generated by Django 4.2.6 on 2023-10-25 07:11

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="lead_text_en",
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name="Introduction En"),
        ),
        migrations.AddField(
            model_name="post",
            name="main_text_en",
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name="Text En"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Title En"),
        ),
        migrations.AlterField(
            model_name="post",
            name="color",
            field=models.CharField(
                choices=[("#ffffff", "White"), ("#000000", "Black")],
                default="#ffffff",
                max_length=7,
                verbose_name="Font Color",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateField(verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Public"),
        ),
        migrations.AlterField(
            model_name="post",
            name="lead_text",
            field=models.TextField(max_length=255, verbose_name="Introduction"),
        ),
        migrations.AlterField(
            model_name="post",
            name="main_text",
            field=markdownx.models.MarkdownxField(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(related_name="posts_tags", to="blog.tag", verbose_name="Tag"),
        ),
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="", verbose_name="Thumbnail"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateField(blank=True, null=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                blank=True, default="#000000", max_length=7, null=True, verbose_name="Background Color"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Tag Name"),
        ),
    ]
