name: Fly Deploy

on:
  push:
    branches:
      - 'your blanch'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: build vue project
        run: npm install && npm run build
        working-directory: ./blog/vue3_frontend
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: printenv > .env
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
      - run: flyctl deploy --remote-only
